name: Build&Tests

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x.x'

      # Build
      - name: Build
        run: dotnet build 'LibraryManagement.API/LibraryManagement.API.csproj' --configuration ${{ env.buildConfiguration }}

      # Test
      - name: Testing
        run: dotnet test 'LibraryManagement.Tests.Integration/LibraryManagement.Tests.Integration.csproj' --configuration ${{ env.buildConfiguration }}

      # Run the Web API in the background
      - name: Run the WebApi in the background
        run: dotnet ${{ github.workspace }}/LibraryManagement.API/bin/${{ env.buildConfiguration }}/LibraryManagement.API.dll &

      # Install Newman
      - name: Install Newman
        run: npm install newman -g

      # Run Postman tests
      - name: Run Postman tests
        run: newman run ${{ github.workspace }}/HotelBooking.postman_collection.json -k -r cli
