name: Newman CLI


on:

  push: 
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: matt-ball/newman-action@master
        with:
          collection: LibraryManagement.Tests.Integration\LibraryManagement.postman_collection.json
          environment: LibraryManagement.Tests.Integration\LibraryManagement.postman_collection.json
