name: Newman CLI


on:

  push: 
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/checkout@v3
        with:
          node-version : '17.x'


      - name: install newman
        run: 
          npm install -g newman



      - name: Run collection
        run:
          newman run LibraryManagement.Tests.Integration/LibraryManagement.postman_collection.json 

      - name: Run the WebApi in the background
        run: CmdLine@2
         inputs:
            script: 'dotnet $(Build.SourcesDirectory)/LibraryManagement.API/bin/$(buildConfiguration)/LibraryManagement.API.dll &'

             
